apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: twin-service
  namespace: iot
  labels:
    app: twin-service
    component: digital-twin
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: twin-service.tailc2013b.ts.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: twin-service
            port:
              number: 8080

