apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nats-ui-ingress
  namespace: nats
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: nats-ui.tailc2013b.ts.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nats-ui
            port:
              number: 31311
