apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ditto-ingress
  namespace: iot
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: ditto.tailc2013b.ts.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ditto-nginx
            port:
              number: 8080

